### PR TITLE
Expose the inner QUIC connection

### LINKED ISSUE #154: Access to low-level `quinn::Connection`
I need access to `peer_identity` and `handshake_data`, and `export_keying_material` fns of the `quinn::Connection` to run some security assertions in the WebTransport handler, but I figured this low-level access could simpler be provided by exposing the whole `quinn::Connection` with the corresponding feature-flag enabled.

---

To provide some additional context: we want to tie the transport security to an AMD SEV-SNP attestation report.

See [AMD SEV SNP spec](https://www.amd.com/content/dam/amd/en/documents/epyc-technical-docs/specifications/56860.pdf) for more info.

For that, we'd want to use key material exports and pass them into the attestation reports alongside our own nonces.
The WebTransport-specific spec for this is still underway, but we can already use it at the QUIC level via `quinn` implementation.
You might want to implement WebTransport TLS Keying Material Exporter at `wtransport` too - I created https://github.com/BiagioFesta/wtransport/issues/155.

### PR DESCRIPTION
**Pull request by MOZGIII**
Closes #154.

### CODE REVIEW

**Review by BiagioFesta — CHANGES_REQUESTED** [review]
Can you please squash the 2 commits together?

**Comment by BiagioFesta** [comment]
Moreover maybe this: https://github.com/BiagioFesta/wtransport/pull/160 might be enough?

**Comment by MOZGIII** [comment]
> Moreover maybe this: #160 might be enough?

No, that's not sufficient, we also figured we need a low level access for our TLS-tweaknig deps...

**Comment by MOZGIII** [comment]
> Can you please squash the 2 commits together?

Done!

**Review by BiagioFesta — APPROVED** [review]

**Comment by im-alfa** [comment]
Hi @BiagioFesta

Is there an estimate for the merge of this PR?

**Comment by BiagioFesta** [comment]
Please rebase so I can merge it

**Comment by im-alfa** [comment]
> Please rebase so I can merge it

I haven't created the PR, so ig @MOZGIII has to do it :S

**Comment by MOZGIII** [comment]
Rebased, sorry for the delay

**Comment by BiagioFesta** [comment]
Thank you!

**Pull request merged**
